CREATE DATABASE sinister CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

USE sinister;

CREATE TABLE users(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    password VARCHAR(128) NOT NULL,
    accessKey VARCHAR(64) DEFAULT NULL
) ENGINE = INNODB;